# NOT REQUIRED version: "2.32.1"

services:
  api:
    build:
      context: ./backend # Cambiado para apuntar a la carpeta backend
      dockerfile: ../Dockerfile # Cambiado para encontrar el Dockerfile en la raíz
    ports:
      - 8000:8000
      # Mount the SQLite database file as a volume so it persists between container restarts
    volumes:
      # The format of this volume mount is: <host_path>:<container_path>:<access_mode> (read-write)
      - ./backend/megafonito.db:/app/megafonito.db:rw
      - ./backend:/app
      # Set environment variables needed for the application
    environment:
      - SECRET_JWT=${SECRET_JWT} # Pass the JWT secret from host environment
