// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7nbv7ksqA9nAgwQ5xPV2ild4LExVFBhs',
    appId: '1:190225013598:web:b88880d17ab98b9cf84dcf',
    messagingSenderId: '190225013598',
    projectId: 'megafonitoauth',
    authDomain: 'megafonitoauth.firebaseapp.com',
    storageBucket: 'megafonitoauth.firebasestorage.app',
    measurementId: 'G-6DR9NSRMR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfuxh_DT4c5rR1--J298TvWCD2M6fAiPo',
    appId: '1:190225013598:android:8f1ee18d15a5f46cf84dcf',
    messagingSenderId: '190225013598',
    projectId: 'megafonitoauth',
    storageBucket: 'megafonitoauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKRPP5njRO1r5GJssu9l-SaQ4O5YOnw3U',
    appId: '1:190225013598:ios:61b0d114e3b74a4ff84dcf',
    messagingSenderId: '190225013598',
    projectId: 'megafonitoauth',
    storageBucket: 'megafonitoauth.firebasestorage.app',
    iosBundleId: 'com.example.flutterMegafonito',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKRPP5njRO1r5GJssu9l-SaQ4O5YOnw3U',
    appId: '1:190225013598:ios:61b0d114e3b74a4ff84dcf',
    messagingSenderId: '190225013598',
    projectId: 'megafonitoauth',
    storageBucket: 'megafonitoauth.firebasestorage.app',
    iosBundleId: 'com.example.flutterMegafonito',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7nbv7ksqA9nAgwQ5xPV2ild4LExVFBhs',
    appId: '1:190225013598:web:76330477fa9509fcf84dcf',
    messagingSenderId: '190225013598',
    projectId: 'megafonitoauth',
    authDomain: 'megafonitoauth.firebaseapp.com',
    storageBucket: 'megafonitoauth.firebasestorage.app',
    measurementId: 'G-ETXR4H17XY',
  );
}
