name: Flutter CI

on:
  push:
    branches:
      - main # Se activa al hacer push a la rama main
    paths:
      - "frontend/**" # Solo si hay cambios en la carpeta frontend

jobs:
  build-apk:
    runs-on: ubuntu-latest # Usamos Ubuntu por su compatibilidad con Flutter

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable" # Usa la versión estable de Flutter

      - name: Generate missing files
        working-directory: ./frontend
        run: flutter create . # Genera las carpetas y archivos faltantes

      - name: Install dependencies
        working-directory: ./frontend
        run: flutter pub get # Instala las dependencias del proyecto

      - name: Build APK
        working-directory: ./frontend
        run: flutter build apk --release # Genera el APK en modo release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: frontend/build/app/outputs/flutter-apk/app-release.apk # Ruta del APK generado
          retention-days: 90 # Optional: Set retention period (default is 90 days)
          compression-level: 9 # Optional: Enable compression (0 = no compression, 9 = max compression)
